id: P191F2184
initial_creation_type: ocr
source_metadata:
  volumes:
    dde47b1eeffc4b96a381ebcd53a8ac4e:
      base_file: v017.txt
      image_group_id: I1PD95862
      title: སྒྲོན་མ་གསལ་བར་བྱེད་པའི་དགོངས་པ་རབ་གསལ་ཞེས་བྱ་བ་བཤད་པའི་ཊཱི་ཀཱ།
      total_pages: 1158
      volume_number: 17
vol2fn:
  v017: v017.txt